### ISSUE TITLE
How to limit actions to be used once in the tree

### ISSUE THREAD

**Issue by AlexisTM** [simpleai-team/simpleai#64]
Dear,

I am learning AI and I am at the beginning.

I would like to limit the use of actions to one time for each. Indeed, I have to find a subset of actions to achieve the goal, but each action can be done only once. 

How should I add that constraint to the actions ?

``` python
from simpleai.search import SearchProblem, breadth_first, depth_first, greedy, astar

class MyPuzzle(SearchProblem):
    def __init__(self, initial_state = 0):
        self.goal = 51
        super(MyPuzzle, self).__init__(initial_state)

    def actions(self, state):
        if(state > self.goal):
            return []
        else :
            return (1,20,30,25,21,32,65,96,30,16,25,18,75,21,1)

    def result(self, state, action):
        return state + action

    def cost(self, state, action, state2):
        return 1

    def is_goal(self, state):
        return state == self.goal

    def heuristic(self, state):
        return self.goal - state
```

**Comment by fisadev** [comment]
To do that, you should carry the list of used actions inside the state. Remember: the state is what keeps track of everything that changes and needs to be remembered during the solution path.

Example based on your case:


```python
from simpleai.search import SearchProblem, breadth_first, depth_first, greedy, astar


class MyPuzzle(SearchProblem):
    def __init__(self, initial_state=(0, (,))):
        self.goal_number = 51
        super(MyPuzzle, self).__init__(initial_state)

    def actions(self, state):
        number, actions_done = state
        if(number > self.goal_number):
            return []
        else :
            all_actions = (1,20,30,25,21,32,65,96,30,16,25,18,75,21,1)
            return [action for action in all_actions if action not in actions_done]

    def result(self, state, action):
        number, actions_done = state
        # convert to list to add the new number, then back to tuples
        actions_done = list(actions_done)
        actions_done.append(action)
        return (state + action, tuple(actions_done))

    def cost(self, state, action, state2):
        return 1

    def is_goal(self, state):
        number, actions_done = state
        return number == self.goal_number

    def heuristic(self, state):
        number, actions_done = state
        return self.goal_number - number
```

**Comment by AlexisTM** [comment]
It is brilliant ! But uses a lot of memory :o

**Comment by fisadev** [comment]
Yes, this uses extra memory, but believe me, it's not too much more. The main issue with this problem is the branching factor: each search node will have **lots** of child nodes, specially in the upper levels of the tree, which makes it grow exponentially. 

Some ideas that can help fix the problem:

* You could try using depth_first search, which in this scenario won't get stuck in infinite loops (because your problem has a depth limit), and will consume far less memory than the others. Have you tried that?

* Does the ordering of the actions affect your problem? if doing action 1 and then action 96 is the same than doing action 96 and then action 1, then the ordering doesn't matter. If that's the case, you could reduce an awful lot the branching factor, by only allowing to use the actions in one specific order. This could reduce the memory and time usage by thousands of times. I could expand on this idea if you have doubts.

* Are you doing tree or graph search? (that is, are you allowing to pass over repeated states?). This could also reduce a lot of the search space (which translate to far less memory and time consumption). This is quite simple, just pass graph_search=True to the search methods.

**Comment by AlexisTM** [comment]
I did not thought about the ordering. Indeed, in my problem, the ordering does not matter at all. I am pretty sure this is my bottleneck since the complexity exponentially increase the complexity ! 

I am allowed to pass over repeated states, I am already using graph_search=True
